- cdntaxreceipts.functions.inc
Removed ts() function for user related data fields such as display name, address fields etc. which was responsible for text changes in Tax Receipt.
> CRM-714: Word Replacement should not change input data

- cdntaxreceipts.functions.inc
sm-dms instance has "In Kind" fund name as "In-Kind" which was not meeting check criteria `if ( $contributiontype->name == 'In-kind' || $contributiontype->name == "In Kind") {` so In-Kind Donation Receipts were not displaying "Description of property" field. Added code which accepts "In-Kind" fund name string with different case-insensitive variations and with special character.
> CRM-1410:DMS - In-Kind Donation Receipts not displaying "Description of property"

- cdntaxreceipts.functions.inc
Previously Re-issued tax receipts did not include "In-Kind Donation" details. With this PR we are fetching in-kind fields for contribution through `cdntaxreceipts_contributions_get_status_inkind($contribution_id)` function and adding "In-Kind Donation" details to receipt array.
> CRM-1060: Re-issued aggregated tax receipts for in kind contributions miss "In-Kind Donation" details

- cdntaxreceipts.functions.inc
When **Custom Thank You Message** is checked and method is **Print** we have added a function which creates individual PDF of selected thank you message. Included pages of that PDF to existing Receipt. Unlink PDF file from temp folder after successful page import.
> CRM-1197: Ability to print 'Thank you' messages when selecting 'Print' as tax receipt delivery method.

- CRM/Cdntaxreceipts/Form/ViewTaxReceipt.php
- CRM/Cdntaxreceipts/Task/IssueAggregateTaxReceipts.php
- CRM/Cdntaxreceipts/Task/IssueAnnualTaxReceipts.php
- CRM/Cdntaxreceipts/Task/IssueSingleTaxReceipts.php
Rather than passing entire value as attribute, passed value in array as one of the attributes.
> CRM-1595:DMS - Charity unable to issue Tax Receipts - Error stating ' From Email' not setup despite it being setup

- cdntaxreceipts.functions.inc
If receipt is in a preview mode , setting static receipt number placeholder with "[receipt_prefix]XXXXXXXX" format.
> CRM-1340: When previewing tax receipts, the tax receipt number should be a static placeholder

- cdntaxreceipts.php
Added an additional check at the time of logo and signature upload that if Image format type (image/jpeg,image/png) doesn't match with extension type (image/jpeg = [.jpg, .jpeg, .jfif, .pjpeg, .pjp], image/png = [.png]) user gets additional notification in the notification bar that **Image extension doesn't match with file type**. If format type is other than jpeg and png user gets notification that **This image type is not supported**. It would not prevent user from uploading image.
> CRM-1456: No Logo or Signature displaying on Tax Receipts despite Images being uploaded

- CRM/Cdntaxreceipts/Task/IssueSingleTaxReceipts.php
- cdntaxreceipts.php
From this code preview popup message will appear on button click, instead of page refresh. On click event sent jQuery ajax request is sent to  **CRM_Canadahelps_ExtensionUtils::singleTaxReceiptPreview** function to count number of tax receipts to be previewed and on success display result in popup message.
> CRM-1168-Incorrect pop-up message appears when a tax receipt is issued after previewing it

- cdntaxreceipts.functions.inc
We have passed one missing  parameter 'tplParams' to function which will convert token value properly.
> CRM-1610-CDN Tax Receipts - Email Single Receipt template needs to get updated - tokens not working

- cdntaxreceipts.functions.inc
When ever new tax receipt get issued for first time will add receipt date parameter value to contribution table using APIV4 update.
> CRM-1270-DMS -Receipts report doesn't include Receipt Date on export (expose Receipt Date in contributions)

- cdntaxreceipts.functions.inc
**Root Cause:** When "CDN Tax Receipts - Thank you Note" TemplateMessage is blank and NULL value was being assigned to $newString rather than String.
**Solution:** Assigned string value to $newString variable if "CDN Tax Receipts - Thank you Note" TemplateMessage is blank.
> CRM-1868:DMS - Charity receiving Error when trying to Issue Tax Receipts in DMS

- CRM/Cdntaxreceipts/Form/Settings.php
- cdntaxreceipts.php
- If receipt Logo/Signature value has relative path in it then keeping that value as is, otherwise appending custom directory path  to Logo/Signature value to access file contents.
> CRM-1860: Broken image icons appear in Receipt Settings page for new charities

- cdntaxreceipts.php
Used already existing function 'Civi::settings()->get('settings_validated_taxreceipts')' which is developed for CRM-1861 to check if receipt settings are correct or not. If not then disable the following actions.
(1)Disable the 'Issue Aggregated Tax Receipts' action from the contributions tab if receipts settings are not validated
(2)Disable the 'Issue Separate Tax Receipts' action from the contributions tab if receipts settings are not validated
(3)Disable the 'Issue Annual Tax Receipts' action from the contacts tab if receipts settings are not validated
> CRM-1918-Disable Receipts issuance if settings not validated

- CRM/Cdntaxreceipts/Form/ViewTaxReceipt.php
- CRM/Cdntaxreceipts/Task/IssueAggregateTaxReceipts.php
- CRM/Cdntaxreceipts/Task/IssueAnnualTaxReceipts.php
- CRM/Cdntaxreceipts/Task/IssueSingleTaxReceipts.php
- cdntaxreceipts.functions.inc
This is not the optimal way to update 'receipt_date' parameter for specific contributions. As CDNTaxreceipt modules require other sessions for code refactoring, at that time will include refactoring of this part of the code aswell.
> CRM-1959-'Issued On' value is not getting updated in 'Edit Contribution Form' if the contribution's tax receipt was replaced with a new one

- CRM/Cdntaxreceipts/Form/Settings.php
If **receipt_prefix** field has value with space then system would provide error message to remove that space.
> CRM-1972:Error appears while issuing a tax receipt if the Receipt Prefix has a space in it

- CRM/Cdntaxreceipts/Form/Settings.php
- CRM/Cdntaxreceipts/Form/ViewTaxReceipt.php
- CRM/Cdntaxreceipts/Task/IssueAggregateTaxReceipts.php
- CRM/Cdntaxreceipts/Task/IssueAnnualTaxReceipts.php
- CRM/Cdntaxreceipts/Task/IssueSingleTaxReceipts.php
- cdntaxreceipts.functions.inc
- info.xml
Version 1.5.1.3
Requires v4.17.0+
CRA Compliance
- CRM-1950: Duplicate receipt should not be sent to archive
- CRM-1959: 'Issued On' value is not getting updated in 'Edit Contribution Form' if the contribution's tax receipt was replaced with a new one
- CRM-1966: Cancelled watermark added multiple times
- CRM-1972: Error appears while issuing a tax receipt if the Receipt Prefix has a space in it
> Version 1.5.1.3

- CRM/Cdntaxreceipts/Task/IssueAggregateTaxReceipts.php
check if most recent contribution is cancelled, and mark as "replace"
> CRM-1990-Receipt not getting replaced for a cancelled In Kind donation through Aggregate Tax Receipt method

- CRM/Cdntaxreceipts/Form/ViewTaxReceipt.php
- CRM/Cdntaxreceipts/Task/IssueAggregateTaxReceipts.php
- CRM/Cdntaxreceipts/Task/IssueSingleTaxReceipts.php
- cdntaxreceipts.functions.inc
For aggregated tax receipt
(1) When I select all of the same transactions on the original receipt, I see 'Cancels and Replaces' with the original tax receipt number on my re-issued tax receipt.
(2) When I have not selected the original transactions, but have selected a combination of the original transactions (it. 3 of 5), or some of the original transactions plus some new transactions, then I received a new tax receipt.
(3)if the aggregate receipt has only one contribution in that case for issuing separate or manage receipts, the 'cancel and replace receipt number' text should be visible.
> CRM-1977-Replacing Aggregate Receipt

- CRM/Cdntaxreceipts/Task/IssueSingleTaxReceipts.php
for canceled aggregated tax receipt
if the aggregate receipt has only a single contribution in the case of issuing separate or manage receipts 'cancel and replace receipt number' text should be visible otherwise in all cases it should be treated like a completely new tax receipt.
> CRM-1993-Able to generate two or more different receipts that replaces the same old one

- cdntaxreceipts.functions.inc
In CiviCRM repository 'receipt.php' file, we have already declared 'setUploadDir(CRM_Core_Config::singleton()->uploadDir);' function into the construct function, therefore removing it from the following places.
> CRM-2002-Unable to issue duplicate tax receipt for a contact whose address has been recently deleted

- CRM/Cdntaxreceipts/Task/IssueSingleTaxReceipts.php
Display an error message when the Nondeductible amount is 0. When the Advantage amount is 100% of the contribution, we show an error message on the contribution view page and the reasons for the ineligible receipt section.
> CRM-2005-Different eligibility displayed in the Receipt Details for the same contact

- CRM/Cdntaxreceipts/Form/ViewTaxReceipt.php
when two contacts get merged, for contribution whose contact got merged to another contact identifies the old deleted contactID(based on cdntaxreceipts_log tabel) , so for that first code will check if the contact is deleted or not. If yes then based on the contribution ID will fetch and update the correct contact ID.
> CRM-1997-Getting an error while clicking the receipt number link in Contribution Details page

- CRM/Cdntaxreceipts/Task/IssueAggregateTaxReceipts.php
Updated condition for 'cancelled_replace_receipt_number' for aggregated tax receipt.
If the Cancelled contribution Receipt List exactly matches with the List of contributions List that case only add 'cancelled_replace_receipt_number'
> CRM-1977-1-Updated condition for 'cancelled_replace_receipt_number' for aggregated tax receipt

- cdntaxreceipts.functions.inc
(1) updated variable value from $receipt to $receiptInfo to avoid confusion between the same name.
(2) added 'contribution_amount', 'receive_date' parameters 
(3) added code to make 'contribution amount' and  'receipt amount' values identical.
> CRM-2051-Total Amount is wrong in Manage Receipt page
